-- ============================================
-- 04. 초기 목표 데이터 삽입
-- ============================================
-- 목적: 전사/부서/직원/거래처 목표 설정
-- 실행일: 2025-10-07
-- 참고: 이 파일은 마이그레이션에서 제외됨
--       실제 목표는 관리자가 백엔드 API를 통해 동적으로 입력

-- ==========================================
-- 📌 사용 방법
-- ==========================================
-- 1. 연간 목표 설정: 매년 초 관리자가 API를 통해 입력
--    - 전사 수금/매출 목표
--    - 부서별 수금/매출 목표
--
-- 2. 월간 목표 설정: 매월 초 관리자가 API를 통해 입력
--    - 전사 수금/매출 목표
--    - 부서별 수금/매출 목표
--
-- 3. 직원별 목표: 부서장이 API를 통해 입력
--    - employees.monthlyCollectionGoal
--    - employees.monthlySalesGoal
--    - employees.annualCollectionGoal
--    - employees.annualSalesGoal
--
-- 4. 거래처별 목표: 영업담당자가 API를 통해 입력
--    - companies.monthlyCollectionGoal
--    - companies.monthlySalesGoal
--    - companies.annualCollectionGoal
--    - companies.annualSalesGoal

-- ==========================================
-- 🔧 테이블 구조 확인
-- ==========================================
-- SELECT * FROM companyGoals;          -- 전사/부서 목표
-- SELECT * FROM employees LIMIT 5;     -- 직원별 목표
-- SELECT * FROM companies LIMIT 5;     -- 거래처별 목표
-- SELECT * FROM changeHistory LIMIT 10; -- 목표 변경 이력

-- ==========================================
-- ⚠️ 주의사항
-- ==========================================
-- - 임의의 목표 금액을 넣지 마세요
-- - 모든 목표는 관리자/부서장/영업담당자가 입력합니다
-- - 목표 입력 시 changeHistory에 자동으로 기록됩니다
